language: node_js
node_js:
  - '6'

env:
  global:
    - CC_TEST_REPORTER_ID=63dd40111983a5eb2e793fff88842e5936ec04c113d117202d387f392e9fd863

cache:
  directories:
  - node_modules

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
 
script:
  - npm run test
  - npm run prod

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
